### ISSUE TITLE
DAS nodes (tracking issue)

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/lazyledger-core#381]
# DAS node types

Now that the MVP DAS light-client is out of the door, we should focus on getting the other node types specified, decide on a few networking and p2p-related questions and actually implement all other node types.

## Experiments:

This section needs further discussion and clarification

- [x] Further clarify performance questions around dht and ipfs usage.
  - [x] https://github.com/lazyledger/lazyledger-core/issues/387, 
  - [x] https://github.com/celestiaorg/lazyledger-core/issues/377

### More on Experiments:

- [x] https://github.com/lazyledger/lazyledger-core/issues/376
- [x] https://github.com/lazyledger/lazyledger-core/issues/382

### Required ADRs, decisions, and components:

- [x] ADR / design doc around different options for block propagation: https://github.com/lazyledger/lazyledger-core/issues/389 (related discussion: https://github.com/lazyledger/lazyledger-core/discussions/384, and previous explorative work [adr001](https://github.com/lazyledger/lazyledger-core/blob/66dd73241e508bc439679afd49683282f8d47b5c/docs/lazy-adr/adr-001-block-propagation.md) under the assumption that validators also do DAS)
- [x] Block-Sync 
- [x] Fast-Sync (almost no changes necessary)
- [x] Everything else around DAS nodes (UX etc), and different kinds of storage nodes: 
  - [x] ~~https://github.com/lazyledger/lazyledger-core/issues/388~~
  - [x] decide on libp2p vs tendermint p2p for the non-consensus nodes
- [x] Decide on https://github.com/lazyledger/lazyledger-core/issues/191
- [x] Decide on: https://github.com/lazyledger/lazyledger-core/issues/189
- [x] Decide on: https://github.com/lazyledger/lazyledger-core/issues/182

### Implementation:
- [x] ~~https://github.com/lazyledger/lazyledger-core/issues/181~~ (we won't need to change consensus messages unless it's necessary for changing block propagation)

### Chores:

- [x] Issue templates to improve communication: https://github.com/lazyledger/lazyledger-core/issues/219

### Nice to haves:

- [x] https://github.com/lazyledger/lazyledger-core/issues/196

**Comment by musalbas** [comment]
Superseded by https://github.com/celestiaorg/lazyledger-core/issues/491

Should this be closed?

**Comment by liamsi** [comment]
Yes, let me go through the few open issues and repriotize them, or move them over to #491, or, close them (if no longer relevant). 

Not sure how to handle the spec-related ones at the top and the more organizational / work-flow related ones (see the unchecked boxes). Ideally, they should also be prioritized and be part of some tracking issue even if they do not block the dev-net (@adlerjohn @musalbas).

**Comment by liamsi** [comment]
OK, moved them over to #491 as well.
